<a href="https://colab.research.google.com/github/mukku787709/CampusX-Mlops2/blob/main/Convolution_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
image = np.array([
    [1,2,3,0,1],
    [0,1,2,3,2],
    [3,0,1,2,1],
    [2,1,3,0,1],
    [1,2,0,1,2]
])
image.shape

kernel = np.array([
    [0,1,4],
    [1,-4,1],
    [0,1,0]
])

def convolve(image,kernel):
  image_h,image_w = image.shape
  kernel_h,kernel_w = kernel.shape
  output_h =  image_h - kernel_h + 1
  output_w = image_w - kernel_w +1
  output = np.zeros((output_h,output_w))

  for i in range(output_h):
    for j in range(output_w):
      output[i,j] = np.sum(image[i:i+kernel_h,j:j+kernel_w] * kernel)

  return output

output = convolve(image,kernel)
print("convolution Output:\n",output)

convolution Output:
 [[12.  0. -2.]
 [14. 15.  5.]
 [ 7. -2. 11.]]


In [ ]:
padding =1
output - 5*5

array([[-13., -25., -27.],
       [-11., -10., -20.],
       [-18., -27., -14.]])

In [24]:
# Adding padding
def pad_image(image, pad):
    return np.pad(image, pad, mode='constant', constant_values=0) # zero padding

pad_image(image, 1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 1, 0],
       [0, 0, 1, 2, 3, 2, 0],
       [0, 3, 0, 1, 2, 1, 0],
       [0, 2, 1, 3, 0, 0, 0],
       [0, 1, 2, 0, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [38]:
# Adding padding
def pad_image(image, pad):
    return np.pad(image, pad, mode='constant', constant_values=0) # zero padding

# Modify convolution to include stride and padding
def convolve_with_padding_and_stride(image, kernel, stride=1, padding=0):
    if padding > 0:
        image = pad_image(image, padding)

    image_h, image_w = image.shape
    kernel_h, kernel_w = kernel.shape[:2]
    output_h = (image_h - kernel_h) // stride + 1
    output_w = (image_w - kernel_w) // stride + 1
    output = np.zeros((output_h, output_w))

    for i in range(0, output_h * stride, stride):
        for j in range(0, output_w * stride, stride):
            output[i // stride, j // stride] = np.sum(
                image[i:i+kernel_h, j:j+kernel_w] * kernel
            )

    return output

# Define a simple 5x5 grayscale image
image = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
])

# Apply the convolution with padding and stride
padded_output = convolve_with_padding_and_stride(image, kernel, stride=1, padding=1)
print("Padded Convolution Output:\n", padded_output)


Padded Convolution Output:
 [[ 4. 10.  9. 18.  6.]
 [12. 15. 18. 15. 10.]
 [ 3. 19. 18. 15. 10.]
 [10. 18.  6. 16.  9.]
 [ 8.  7. 13.  6.  0.]]


In [39]:
def max_pooling(image,pool_size,stride):
   image_h,image_w = image.shape
   output_h = (image_h - pool_size)//stride +1
   output_w = (image_w -pool_size)//stride +1
   output = np.zeros((output_h,output_w))


   for i in range(0,output_h * stride,stride):
      for j in range(0,output_w * stride,stride):
        output[i//stride,j//stride] = np.sum(
            image[i:i+pool_size,j:j+pool_size]
        )
   return output

   image = np.array([
      [1,2,3,0,1],
      [0,1,2,3,2],
      [3,0,1,2,1],
      [2,1,3,0,0],
      [1,2,0,1,2]
  ])


pooled_output = max_pooling(image,pool_size=2,stride=2)
print("Max Polling Output:/n",pooled_output)




Max Polling Output:/n [[4. 8.]
 [6. 6.]]


In [40]:
import numpy as np
image = np.array([
    [[1,0,2],[2,1,1],[3,2,0],[0,1,1],[1,0,2]],
    [[0,1,0],[1,0,1],[2,2,2],[3,1,3],[2,0,1]],
    [[3,0,2],[0,1,0],[1,0,1],[2,2,2],[1,0,0]],
    [[2,1,1],[1,0,2],[3,3,1],[0,1,0],[0,2,1]],
    [[1,2,2],[2,1,0],[0,0,1],[1,2,2],[2,1,1]]
])

image.shape

(5, 5, 3)

In [41]:
kernel = np.array([
    [[0,1,0],[1,-1,1],[0,1,0]],
    [[1,0,1],[0,-1,0],[1,0,1]],
    [[0,1,0],[1,1,1],[0,1,0]]
])

kernel.shape

(3, 3, 3)

In [42]:
image_h,image_w,image_c = image.shape

print(image_h,image_w,image_c)
kernel_h,kernel_w,kernel_c = kernel.shape
print(kernel_h,kernel_w,kernel_c)
output_h = image_h - kernel_h + 1
output_w = image_w - kernel_w + 1
output = np.zeros((output_h,output_w,1))
output.shape


5 5 3
3 3 3


(3, 3, 1)

In [43]:
for k in range(image_c):
        for i in range(output_h):
          for j in range(output_w):
            output[i,j] = np.sum(image[i:i+kernel_h,j:j+kernel_w,k] * kernel)

output

array([[[10.],
        [12.],
        [12.]],

       [[16.],
        [15.],
        [11.]],

       [[ 8.],
        [11.],
        [15.]]])

In [44]:
import numpy as np
image = np.array([
    [[1,0,2],[2,1,1],[3,2,0],[0,1,1],[1,0,2]],
    [[0,1,0],[1,0,1],[2,2,2],[3,1,3],[2,0,1]],
    [[3,0,2],[0,1,0],[1,0,1],[2,2,2],[1,0,0]],
    [[2,1,1],[1,0,2],[3,3,1],[0,1,0],[0,2,1]],
    [[1,2,2],[2,1,0],[0,0,1],[1,2,2],[2,1,1]]
])

image.shape

kernel = np.array([
    [[0,1,0],[1,-1,1],[0,1,0]],
    [[1,0,1],[0,-1,0],[1,0,1]],
    [[0,1,0],[1,1,1],[0,1,0]]
])

kernel.shape

def convolve_rgb(image,kernel):
  image_h,image_w,image_c = image.shape
  kernel_h,kernel_w,kernel_c = kernel.shape
  output_h = image_h - kernel_h + 1
  output_w = image_w - kernel_w + 1
  output = np.zeros((output_h,output_w,1))
  output.shape

  for k in range(image_c):
        for i in range(output_h):
          for j in range(output_w):
            output[i,j] = np.sum(image[i:i+kernel_h,j:j+kernel_w,k] * kernel)

  return output

output = convolve_rgb(image,kernel)
print("Convolution Output:/n",output)


Convolution Output:/n [[[10.]
  [12.]
  [12.]]

 [[16.]
  [15.]
  [11.]]

 [[ 8.]
  [11.]
  [15.]]]


In [45]:
import tensorflow as tf
from tensorflow.keras import layers,models

input_shape =(100,100,3)
model = models.Sequential()
model.add(layers.Input(shape=input_shape))
model.add(layers.Conv2D(16,(3,3),padding='same',strides=1,activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2), strides=2))

model.add(layers.Conv2D(32,(3,3),padding='same',strides=1,activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=2))
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_13 (Conv2D)                   │ (None, 100, 100, 16)        │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_11 (MaxPooling2D)      │ (None, 50, 50, 16)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 50, 50, 32)          │           4,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 25, 25, 32)          │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)